//// <auto-generated />
//using ClashBard.Tow.DataAccess;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace ClashBard.Tow.DataAccess.Migrations
//{
//    [DbContext(typeof(TowDbContext))]
//    partial class TowDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618

//#pragma warning restore 612, 618
//        }
//    }
//}
