using ClashBard.Tow.Models;
using ClashBard.Tow.Models.TowTypes;

namespace ClashBard.Tow.Models.SpecialRules;

public class MultipleWounds2 : TowSpecialRule
{
    private static string ShortDescription = "Causes 2 wounds";
    private static string LongDescription = "Each unsaved wound inflicted by an attack with this special rule is multiplied by the number shown in brackets after the name of this special rule (shown here as 'X'). For example, Multiple Wounds (2) would mean that each unsaved wound would cause the target to lose two Wounds. Where the number of Multiple Wounds is generated by a dice roll, roll separately for each unsaved wound. Note that excess wounds caused to a model will have no additional effect unless that model is a character, in which case this special rule counts for Overkill. Excess wounds do not 'spill over' onto other models in the unit.";

    public MultipleWounds2()
        : base(TowSpecialRuleType.MultipleWounds2,
            ShortDescription,
            LongDescription, 
            printShortDescription: false)
    {

    }
}
